name: qibla_finder_kids
description: Aplikasi Qibla Finder untuk Anak-anak dengan tema yang menyenangkan
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Fonts
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0

  # Qibla & Prayer Times
  flutter_qiblah: ^3.1.0+1
  adhan: ^2.0.0+1
  geolocator: ^13.0.4
  
  # Internationalization
  intl: ^0.20.2
  
  # Storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Uncomment untuk menambahkan assets
  # assets:
  #   - assets/images/
  #   - assets/icons/